### PR TITLE
Feat: block unsafe browser

### PR DESCRIPTION
**Pull request by SukkaW**
- Block Mobile QQ Browser for safety reason
- Block QQ Browser for `Fetch` issue
- Block WeChat for safety reason
- Block UC Browser for its outdated stupid kernel
- Block MIUI Browser for its blocking websites
- Block 360 Browser for safety reason

It can also directs visitors to download Firefox & Chrome.

### CODE REVIEW

**Comment by SukkaW** [comment]
@SukkaW @kinokonominoco

**Comment by laurieryayoi** [comment]
@SukkaW UC和QQ应该可以了

**Comment by ruich97** [comment]
@SukkaW 360呢？

**Comment by SukkaW** [comment]
@ruich97 检测 360 浏览器需要引入专门的库

**Comment by CGDF-Github** [comment]
360的特征一直在变，后期维护恐怕不会太简单

**Comment by SukkaW** [comment]
> 360的特征一直在变，后期维护恐怕不会太简单

@CGDF-Github 这个办法适用于 16 年以来至今的所有 360 浏览器，这个特征应该没有这么快没掉

**Comment by SakuraSa233** [comment]
These code would work better:

```JavaScript
/* previous code*/
if (navigator.userAgent.toLowerCase().indexOf('miuibrowser') !== -1) {
    window.alert('MIUI 浏览器屏蔽了本站部分内容的访问\n为了您能更好地浏览本站，我们推荐您使用 Chrome 或 Firefox 浏览器。');
    document.getElementsByTagName('body')[0].innerHTML = browserHTML;
} else if (navigator.userAgent.toLowerCase().indexOf('ucbrowser') !== -1) {
    window.alert('UC 浏览器使用极旧的内核，而本网站使用了一些新的特性。\n为了您能更好地浏览本站，我们推荐您使用 Chrome 或 Firefox 浏览器。');
    bodyEl.innerHTML = browserHTML;
} else if (navigator.userAgent.toLowerCase().indexOf('tbs') !== -1) {
    if ((navigator.userAgent.toLowerCase().indexOf('micromessenger') !== -1) || (navigator.userAgent.toLowerCase().indexOf('wechat') !== -1)) {
        window.alert('为了您的人身安全，我们禁止您使用微信访问本站，我们推荐您通过 Chrome 或 Firefox 浏览器访问本站。');
        bodyEl.innerHTML = tbsHTML;
    } else if (navigator.userAgent.toLowerCase().indexOf('mqqbrowser') !== -1) {
        window.alert('为了您的人身安全，我们禁止您使用手机QQ访问本站，我们推荐您通过 Chrome 或 Firefox 浏览器访问本站。');
        bodyEl.innerHTML = tbsHTML;
    }
} else if (navigator.userAgent.toLowerCase().indexOf('qqbrowser') !== -1) {
    window.alert('QQ 浏览器内核存在严重缺陷。\n为了您能更好地浏览本站，我们推荐您使用 Chrome 或 Firefox 浏览器。');
    bodyEl.innerHTML = browserHTML;
} else if (new Browser().browser == '360' || new Browser().browser == '360EE' || new Browser().browser == '360SE') {
    window.alert('为了您的人身安全，我们禁止您使用 360 浏览器访问本站，我们推荐您通过 Chrome 或 Firefox 浏览器访问本站。');
    bodyEl.innerHTML = browserHTML;
}
```
And the js file should be put after `<body>` tag, or it won't work.

**Comment by SukkaW** [comment]
@SakuraSa233 Wechat & Mobile QQ do not contain `tbs` in their User-Agent String.
I will push a new commit to fix `<body>` tag undefined issue.

**Comment by SakuraSa233** [comment]
@SukkaW As my test, `tbs` is actually existed in User-Agent. The code also works well.

**Pull request merged**
